# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'InstantSearch-Core-Swift', :path => '/Users/robertmogos/Dev/instantsearch-core-swift'
  pod 'Cosmos', '~> 15.0.0'
  pod 'Nuke', '~> 6.1.0'
 pod 'InstantSearch-iOS', '~> 2.1.0'

end
